name: Flutter Analysis

on: [push, pull_request]

jobs:
  lint_and_format:
    name: Lint, Format, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Run dart format
        run: |
          dart format --output=none --set-exit-if-changed .
          if [ $? -ne 0 ]; then
            echo "Formatting issues found. Please run 'dart format .' locally to fix them."
            exit 1
          else
            echo "No formatting issues found."
          fi

      - name: Run dart analyze
        run: flutter analyze

      - name: Run dart lint
        run: dart pub run lints

      - name: Run tests
        run: flutter test
